# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key    = "us-east-1/terraform/./terraform.tfstate"
    region = "us-east-1"
    bucket = "terraform-dev-basic-example-tfstate"
  }
}
